# Generated by Django 3.0.5 on 2021-03-29 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.TextField(max_length=256)),
                ('email', models.EmailField(max_length=64)),
                ('awards', models.TextField(max_length=128)),
                ('youtube', models.URLField()),
                ('linkedin', models.URLField()),
                ('twitter', models.URLField()),
                ('facebook', models.URLField()),
                ('instagram', models.URLField()),
                ('location', models.CharField(max_length=128)),
            ],
        ),
    ]
