# Generated by Django 3.0.5 on 2021-03-29 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addform',
            name='awards',
            field=models.TextField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='addform',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='addform',
            name='instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='addform',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='addform',
            name='twitter',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='addform',
            name='youtube',
            field=models.URLField(blank=True),
        ),
    ]
